name: Build python app and scan with sonarqube

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Sonarqube Scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
 #     - name: Setup Python
 #       uses: actions/setup-python@v2
 #       with:
 #         python-version: 3.9
 #     - name: Install tox and any other packages
 #       run: pip install tox
 #     - name: Run tox
 #       run: tox -e .
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v3
      - name: Run Scanner
        run: sonar-scanner
           -Dsonar.projectKey=python-project 
           -Dsonar.sources=$GITHUB_WORKSPACE 
           -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} 
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
           -Dsonar.python.coverage.reportPaths=coverage.xml
